version: '2.2'
services:
    app:
        build: '.'
        image: 'gedgo_app'
        env_file: '.env'
        container_name: 'gedgo_app'
        command: ['python', 'manage.py', 'runserver', '0.0.0.0:8000']
        # command: ['uvicorn', '--host=0.0.0.0', '--reload', 'asgi:application']
        ports:
            - '8000:8000'
        volumes:
            - './:/app'
            - '.data/:/data'
    web:
        image: 'nginx:alpine'
        command: 'nginx -g "daemon off;"'
        volumes:
            - './gedgo-web.conf:/etc/nginx/conf.d/default.conf:ro'
            - './.files:/src/files:ro'
        ports:
            - '80:80'
        links:
            - 'app'
